### ISSUE TITLE
Bug: Can't set custom font when modifying BaseToast

### ISSUE THREAD

**Issue by nsdub** [calintamas/react-native-toast-message#124]
Custom `fontFamily` values passes to the style props of BaseToast are ignored.

Example: 

```
      <BaseToast
        {...rest}
        style={{ borderLeftColor: Constants.ACCENT }}
        leadingIcon={require('../../assets/icons/info.png') }
        text1={text1}
        text1Style={{
          fontFamily: 'mort-regular',
          color: 'black',
          fontSize: scale(14),
        }}
      />
```

Other style properties such as `color` and `fontSize` are respected.

**Comment by nsdub** [comment]
A bit more info...

Intermittently this error will be thrown:

```
Warning: Failed prop type: Invalid props.text1Style key `fontFamily` supplied to `BaseToast`.
Bad object: {
  "fontFamily": "mort-regular",
  "color": "#363636",
  "fontSize": 15.70909090909091
}

**Comment by nsdub** [comment]
I don't typescript, but it seems like the problem might be that `text1Style` and `text2Style` are given `ViewStyle` types instead of `TextStyle`

Relevant code:
https://github.com/calintamas/react-native-toast-message/blob/c11450d4cb4b8f31d7f810c9711ecd4d83f65362/index.d.ts#L25

**Comment by arcyn1c** [comment]
> I don't typescript, but it seems like the problem might be that `text1Style` and `text2Style` are given `ViewStyle` types instead of `TextStyle`
> 
> Relevant code:
> 
> https://github.com/calintamas/react-native-toast-message/blob/c11450d4cb4b8f31d7f810c9711ecd4d83f65362/index.d.ts#L25

Correct. https://github.com/calintamas/react-native-toast-message/pull/127 should fix this. Hopefully it can be merged soon? cc @calintamas

**Comment by calintamas** [comment]
merged #127 now. It will be part of `v1.4.3`

**Comment by matmac** [comment]
Regression. This bug is back again or so it seems since I'm trying to set the style for **text2style** and nothing happens.
`"react-native-toast-message": "^2.1.5"`
```
<InfoToast
        {...props}
        contentContainerStyle={{paddingHorizontal: 16}}
        style={{ marginTop:40, borderLeftColor: '#2979FF' }}
        text1Style={{
          fontSize: 16,
          fontWeight: '400',
        }}
        text2style={{
          fontSize: 16,
          fontWeight: '300',
        }}
      />
```
The weight is respected but **fontSize** is not.

<img width="415" alt="Screenshot 2023-01-31 at 20 04 02" src="https://user-images.githubusercontent.com/1344921/215857833-b6f630c8-281b-467a-af56-cd163dd86bae.png">

@calintamas
