### ISSUE TITLE
getting last toast along with native prompt 

### ISSUE THREAD

**Issue by ijharansari2020** [calintamas/react-native-toast-message#149]
![WhatsApp Image 2021-02-15 at 8 30 36 PM](https://user-images.githubusercontent.com/75674031/107962290-cb509700-6fcc-11eb-969e-b42e24fc5658.jpeg)
Last Toast is coming if permission related prompt open, tried to rename ref but no luck ..

**Comment by calintamas** [comment]
Hi @ijharansari2020, can you add a code sample (how is the toast set up, how is the prompt set up, etc)

**Comment by ijharansari2020** [comment]
> Hi @ijharansari2020, can you add a code sample (how is the toast set up, how is the prompt set up, etc)
have added this
 `<Toast ref={(ref) => Toast.setRef(ref)} />`


imported this import Toast from 'react-native-toast-message';

**Comment by calintamas** [comment]
Is the Toast component rendered inside the modal?

**Comment by ijharansari2020** [comment]
no normal page . whatever is last toast its coming

**Comment by calintamas** [comment]
My questions is: where are you rendering `<Toast />` on app's Root?

**Comment by khelifioussama** [comment]
> Is the Toast component rendered inside the modal?

Hello , There is a probleme rendering Toast inside modal ?

I am rendering the Toast inside a Custom Modal who is using the Screen with SafeAreaView as a child and I got Error : Cannot read property 'show' of null

**Comment by calintamas** [comment]
Yes, it should be rendered on app's entry point (along with everything that's rendered there, like navigation). 

Also, when a Modal is visible and you trigger `Toast.show()`, it will show up behind the Modal (since that's where it is in the View hierarchy)

**Comment by ijharansari2020** [comment]
> Yes, it should be rendered on app's entry point (along with everything that's rendered there, like navigation).
> 
> Also, when a Modal is visible and you trigger `Toast.show()`, it will show up behind the Modal (since that's where it is in the View hierarchy)

im not calling Toast.show() but it comes when there is Native prompt

**Comment by calintamas** [comment]
The answer above was to @khelifioussama's question.

@ijharansari2020 where are you rendering <Toast />? Make sure it's not being wrapped by anything rather than the main View container

**Comment by Angelinodc71** [comment]
Something very similar happens to me, I get the last message by logging in with Google. @calintamas 
I have a separate component:

export function errorToast(title: string='Error', message?: string, position: any='top') {
  Toast.show({
    type: 'error',
    position: position,
    visibilityTime: 3000,
    text1: title,
    text2: message,
  });
}

And I call it on other screens like this:
errorToast('Introduce un número de teléfono valido', '');

**Comment by developmentFlykube** [comment]
Same issue here, has anyone managed to fix it?

**Comment by calintamas** [comment]
@Angelinodc71 @developmentFlykube Can you post the code to reproduce the issue? The code where the `Toast` instance is rendered

**Comment by developmentFlykube** [comment]
Hey dude, here is in my App.tsx, on the main render:
`
return (
      <View style={{ backgroundColor: "#0000", width: "100%", height: "100%" }}>

        <NavigationContainer
          ref={GlobalVariables.navigationRef}
          onReady={() => this.state.routeNameRef.current = GlobalVariables.navigationRef.current.getCurrentRoute().name}
          onStateChange={() => {
            const previousRouteName = this.state.routeNameRef.current;
            const currentRouteName = GlobalVariables.navigationRef.current.getCurrentRoute().name;
            console.log("Current: " + currentRouteName);
            console.log("Previous: " + previousRouteName);
            // Save the current route name for later comparision
            this.state.routeNameRef.current = currentRouteName;
            GlobalVariables.current_route = currentRouteName;
            // SAVE DATA INTO THE STORE
            this.props.getNavigationRoute(currentRouteName, previousRouteName);
          }}
        >
          <AuthStack />
        </NavigationContainer>
        <Toast ref={(ref) => Toast.setRef(ref)} />

      </View>
    );
`
Here I have a global function to create a toast wherever i need it:
`
export function errorToast(title: string='Error', message?: string, position: any='top') {
  Toast.show({
    type: 'error',
    position: position,
    visibilityTime: 3000,
    text1: title,
    text2: message,
  });
}
`
This is the way I call it:
`errorToast('Please, select a drink');`

Thanks for the answer!

**Comment by calintamas** [comment]
@developmentFlykube make sure to render the Toast inside `NavigationContainer`
https://github.com/calintamas/react-native-toast-message#how-to-render-the-toast-when-using-react-navigation

**Comment by stanislavpoleshuk** [comment]
Hey! I have a similar problem. On android when calling the native Share module. Toast sticks out
<img width="511" alt="Снимок экрана 2021-03-25 в 12 00 04" src="https://user-images.githubusercontent.com/47532425/112455235-33c82c00-8d62-11eb-83fd-55886999f819.png">

**Comment by calintamas** [comment]
I'll take a look as soon as I can

**Comment by aravi365** [comment]
Any updates or workarounds for this issue? It appears random only, like Not on every android device but on many!

**Comment by sshapoval** [comment]
Hello! I have the same issue. My NavigationContainer looks like this
 `<NavigationContainer ref={navigationRef}>`
        `<RootStackNavigator />`
      `<Toast config={toastConfig} ref={ref => Toast.setRef(ref)} />`
    `</NavigationContainer>`

**Comment by glinda93** [comment]
Same issue here

**Comment by zetamorph** [comment]
same

**Comment by shabith** [comment]
Hi @aravi365, do we have a solution for this? I have implemented it by following this - https://github.com/calintamas/react-native-toast-message#how-to-render-the-toast-when-using-react-navigation and  I'm facing this issue. 

Whenever I navigate to the next screen, I'm getting my old toast message appearing on the screen.

**Comment by Md-Mudassir47** [comment]
same issue

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

Docs on how to render the Toast - [Quick start](https://github.com/calintamas/react-native-toast-message/blob/master/docs/quick-start.md).

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!

**Comment by Md-Mudassir47** [comment]
@calintamas still facing the same issue even after the upgrade.

**Comment by slatqh** [comment]
Don't know if it's make sense to anybody, but I just downgrade to 2.0.0 version and it solve that issue for me, without braking any existing functionality in our project.

**Comment by elabayoub** [comment]
Solution by Mathieu Creusot, here is the patch:
https://github.com/calintamas/react-native-toast-message/commit/0eb3a015dc25639f5b14a0d600f5644050586c90

**Comment by israr-shaikh** [comment]
Best hack found.
Kindly follow the below steps to handle it.

```
Toast.hide();
setTimeout(() => {
  --- call native prompt here ---
}, 500);
```

This will help to tackle the issue.

**Comment by rohitiziss** [comment]
Any solution, I am facing the same issue.
Thanks in advance

**Comment by Thaimay** [comment]
> Solution by Mathieu Creusot, here is the patch: [0eb3a01](https://github.com/calintamas/react-native-toast-message/commit/0eb3a015dc25639f5b14a0d600f5644050586c90)

This solution work for me. Thanks, here the patch-package.

[react-native-toast-message+2.2.0.patch](https://github.com/calintamas/react-native-toast-message/files/15109123/react-native-toast-message%2B2.2.0.patch)
