### ISSUE TITLE
visibilityTime not working

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [calintamas/react-native-toast-message#170]
Whichever value for the visibilityTime prop, i give, the duration of the toast remains the same. My code:                                               AnimatedToast.show({
      type: AnimatedToastTypes.OrderTemplateCopied,
      visibilityTime: 1000,
      ...ANIMATED_TOAST_CONFIG[AnimatedToastTypes.OrderTemplateCopied]
    });

**Comment by jo-rdan** [comment]
I am getting the same error

**Comment by calintamas** [comment]
`visibilityTime` only works in conjunction with `autoHide: true`. Is this the case?

**Comment by jo-rdan** [comment]
@calintamas Hi, yes it is the case for me

```
if (response.status === 200)
        return Toast.show({
          type: "success",
          text1: "Success",
          text2: response.data.message,
          visibilityTime: 2000,
          autoHide: true,
          position: "bottom",
        });
```

**Comment by calintamas** [comment]
@jo-rdan Ok, thanks for the quick response, I'll take a look as soon as I can

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!

**Comment by pierroo** [comment]
@calintamas actually I am still facing the issue even with v2.0.1 (which doesn't seem to mention anything related to visibilityTime?)

regardless of the value I put in it, the toast always displays for around 7000ms; which is quite a lot
